# Generated by Django 3.2.7 on 2021-10-13 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('cc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cc_numeroPersonas', models.IntegerField(verbose_name='Numero personas')),
                ('cc_precioTotal', models.FloatField(verbose_name='Precio total')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('ciu_nombre', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nombre ciudad')),
                ('ciu_pais', models.CharField(max_length=20, verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Identificacion')),
                ('usu_tipoId', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjeria'), ('NIT', 'NIT')], max_length=50, verbose_name='Tipo identificacion')),
                ('usu_nombreUsuario', models.CharField(max_length=60, unique=True, verbose_name='Nombre usuario')),
                ('password', models.CharField(max_length=256, verbose_name='Contraseña')),
                ('usu_nombre', models.CharField(max_length=20, verbose_name='Nombres')),
                ('usu_apellido1', models.CharField(max_length=40, verbose_name='Primer Apellido')),
                ('usu_apellido2', models.CharField(max_length=40, verbose_name='Segundo Apellido')),
                ('usu_email', models.EmailField(max_length=60, verbose_name='Email')),
                ('usu_telefonoCelular', models.CharField(max_length=20, verbose_name='Telefono Celular')),
                ('usu_pais', models.CharField(max_length=20, verbose_name='Pais')),
                ('usu_ciudad', models.CharField(max_length=20, verbose_name='Ciudad')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tour_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tour_nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('tour_descripcion', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('tour_precio', models.FloatField(verbose_name='Precio')),
                ('tour_fechaHoraInicio', models.DateTimeField(default='2021-01-01T00:00:00Z', verbose_name='Fecha inicio')),
                ('tour_fechaHoraFin', models.DateTimeField(default='2021-01-02T00:00:00Z', verbose_name='Fecha fin')),
                ('tour_duracionHoras', models.IntegerField(verbose_name='Duracion')),
                ('tour_transporte', models.CharField(choices=[('PIE', 'A pie'), ('BICI', 'Bicicleta'), ('MOTO', 'Moto'), ('BUS', 'Bus'), ('CAR', 'Carro'), ('LAN', 'Lancha'), ('BAR', 'Barco'), ('AV', 'Avion')], default='A pie', max_length=4, verbose_name='Transporte')),
                ('tour_alimentacion', models.CharField(max_length=100, verbose_name='Alimentacion')),
                ('tour_hospedaje', models.CharField(choices=[(1, 'Si'), (2, 'No')], default='No', max_length=2, verbose_name='Hospedaje')),
                ('tour_kilometros', models.IntegerField(verbose_name='Kilometros')),
                ('tour_inicio', models.CharField(max_length=60, verbose_name='Inicio')),
                ('tour_fin', models.CharField(max_length=60, verbose_name='Fin')),
                ('ciu_nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tour_ciudad', to='TourApp.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_metodoPago', models.CharField(choices=[('PayU', 'PayU'), ('Visa', 'Visa'), ('MC', 'Master Card'), ('AE', 'American Express'), ('DC', 'Diners Club'), ('PSE', 'Pagos Seguros en Línea')], max_length=40, verbose_name='Método Pago')),
                ('com_numeroCuenta', models.BigIntegerField(verbose_name='Número Cuenta')),
                ('com_confirmarPago', models.CharField(choices=[(1, 'Sí'), (2, 'No'), (3, 'Por Confirmar')], default='Por confirmar', max_length=20, null=True, verbose_name='Confirmar pago')),
                ('com_fechaPago', models.DateTimeField(default='2021-01-02T00:00:00Z', null=True, verbose_name='Fecha Pago')),
                ('usu_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Com_id', to='TourApp.carrito')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='cc_tour_nombre',
            field=models.ForeignKey(max_length=60, on_delete=django.db.models.deletion.CASCADE, related_name='Carrito_tour', to='TourApp.tour'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='cc_usu_id',
            field=models.ForeignKey(max_length=60, on_delete=django.db.models.deletion.CASCADE, related_name='Carrito_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
