# Generated by Django 3.2.7 on 2021-10-07 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('ciu_nombre', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nombre ciudad')),
                ('ciu_pais', models.CharField(max_length=20, verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usu_nombreUsuario', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True, verbose_name='Nombre usuario')),
                ('usu_contrasena', models.CharField(max_length=256, verbose_name='Contraseña')),
                ('usu_nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('usu_apellido1', models.CharField(blank=True, max_length=40, null=True, verbose_name='Primer Apellido')),
                ('usu_apellido2', models.CharField(blank=True, max_length=40, null=True, verbose_name='Segundo Apellido')),
                ('usu_email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='Email')),
                ('usu_telefonoCelular', models.IntegerField(blank=True, null=True, verbose_name='Telefono Celular')),
                ('usu_pais', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pais')),
                ('usu_ciudad', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ciudad')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tour_nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('tour_descripcion', models.CharField(max_length=250)),
                ('tour_precio', models.FloatField()),
                ('tour_fechaHoraInicio', models.DateTimeField(default='2021-01-01T00:00:00Z')),
                ('tour_fechaHoraFin', models.DateTimeField(default='2021-01-02T00:00:00Z')),
                ('tour_duracionHoras', models.IntegerField()),
                ('tour_transporte', models.CharField(choices=[('PIE', 'A pie'), ('BICI', 'Bicicleta'), ('MOTO', 'Moto'), ('BUS', 'Bus'), ('CAR', 'Carro'), ('LAN', 'Lancha'), ('BAR', 'Barco'), ('AV', 'Avion')], default='A pie', max_length=4)),
                ('tour_alimentacion', models.CharField(max_length=100)),
                ('tour_hospedaje', models.CharField(choices=[(1, 'Si'), (2, 'No')], default='No', max_length=2)),
                ('tour_kilometros', models.IntegerField()),
                ('tour_inicio', models.CharField(max_length=60)),
                ('tour_fin', models.CharField(max_length=60)),
                ('ciu_nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tour_ciudad', to='TourApp.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_numeroPersonas', models.IntegerField(verbose_name='Numero personas')),
                ('cc_precioTotal', models.FloatField(verbose_name='Precio total')),
                ('cc_tour_nombre', models.ForeignKey(max_length=60, on_delete=django.db.models.deletion.CASCADE, related_name='Carrito_tour', to='TourApp.tour')),
                ('cc_usu_nombreUsuario', models.ForeignKey(max_length=60, on_delete=django.db.models.deletion.CASCADE, related_name='Carrito_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
